package com.fanli.nebula.wormhole.common.utils.confloader.constant;

import java.text.SimpleDateFormat;

/**
 * Created by hongdi.tang on 14-3-5.
 */
public class DateConst {
    public static final SimpleDateFormat LONG_DF_FOR_FILENAME = new SimpleDateFormat("yyyyMMddHHmmssSSS");
    public static final SimpleDateFormat LONG_DF = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS");
    public static final SimpleDateFormat SHORT_DF = new SimpleDateFormat("HH:mm:ss.SSS");
    public static final SimpleDateFormat DAY_DF = new SimpleDateFormat("yyyy-MM-dd");
    public static final SimpleDateFormat DAY_DF8 = new SimpleDateFormat("yyyyMMdd");
    public static final SimpleDateFormat MONTH_DF = new SimpleDateFormat("yyyy-MM");
    public static final SimpleDateFormat MONTH_DF8 = new SimpleDateFormat("yyyyMM");
    public static final SimpleDateFormat YEAR_DF = new SimpleDateFormat("yyyy");
    public static final SimpleDateFormat MM_DF = new SimpleDateFormat("MM");
    public static final SimpleDateFormat DD_DF = new SimpleDateFormat("dd");

    public static final String COMMON_VARS_CAL_PREFIX = "CAL_";

    public static final String DEFAULT_HP_DT = "3000-12-31";

    public static enum BATCH_CAL_VARS {
        CAL_YYYYMM_01,CAL_YYYYMM_LD,
        CAL_YYYYMMDD_YESTERDAY,CAL_YYYYMMDD_TODAY,CAL_YYYYMMDD_DEFAULT_HP_DT,
        CAL_YYYYMM_YESTERDAY,CAL_YYYYMM_TODAY,CAL_YYYY_YESTERDAY,CAL_YYYY_TODAY,
        CAL_MM_YESTERDAY,CAL_MM_TODAY,CAL_DD_YESTERDAY,CAL_DD_TODAY,CAL_YYYYMMDD,CAL_MM,CAL_DD,
        CAL_YYYYMMDD_P1D, CAL_YYYYMMDD_P2D,CAL_YYYYMMDD_P3D, CAL_YYYYMMDD_P4D,CAL_YYYYMMDD_P5D,CAL_YYYYMMDD_P6D, CAL_YYYYMMDD_P7D,
        CAL_YYYYMMDD_P8D, CAL_YYYYMMDD_P9D,CAL_YYYYMMDD_P10D, CAL_YYYYMMDD_P11D,CAL_YYYYMMDD_P12D,CAL_YYYYMMDD_P13D, CAL_YYYYMMDD_P14D,
        CAL_YYYYMMDD_P15D, CAL_YYYYMMDD_P16D,CAL_YYYYMMDD_P17D, CAL_YYYYMMDD_P18D,CAL_YYYYMMDD_P19D,CAL_YYYYMMDD_P20D, CAL_YYYYMMDD_P21D,
        CAL_YYYYMMDD_P22D, CAL_YYYYMMDD_P23D,CAL_YYYYMMDD_P24D, CAL_YYYYMMDD_P25D,CAL_YYYYMMDD_P26D,CAL_YYYYMMDD_P27D, CAL_YYYYMMDD_P28D,CAL_YYYYMMDD_P29D,CAL_YYYYMMDD_P30D,
        CAL_YYYYMMDD_P1M, CAL_YYYYMMDD_P2M, CAL_YYYYMMDD_P3M, CAL_YYYYMMDD_P4M,CAL_YYYYMMDD_P5M, CAL_YYYYMMDD_P6M, CAL_YYYYMMDD_P7M, CAL_YYYYMMDD_P8M, CAL_YYYYMMDD_P9M, CAL_YYYYMMDD_P10M, CAL_YYYYMMDD_P11M, CAL_YYYYMMDD_P12M,
        CAL_YYYYMMDD_P1Y, CAL_YYYYMMDD_P2Y, CAL_YYYYMM, CAL_YYYYMM_P1D, CAL_YYYYMM_P2D, CAL_YYYYMM_P1M, CAL_YYYYMM_P2M, CAL_YYYYMM_P1Y, CAL_YYYYMM_P2Y, CAL_YYYY, CAL_YYYY_P1D, CAL_YYYY_P2D, CAL_YYYY_P1M, CAL_YYYY_P2M, CAL_YYYY_P1Y, CAL_YYYY_P2Y, CAL_YYYYMMDD_N1D, CAL_YYYYMMDD_N2D, CAL_YYYYMMDD_N1M, CAL_YYYYMMDD_N2M, CAL_YYYYMMDD_N1Y, CAL_YYYYMMDD_N2Y,  CAL_YYYYMMDD_P1DOW, CAL_YYYYMMDD_P2DOW, CAL_YYYYMMDD_P3DOW, CAL_YYYYMMDD_P4DOW, CAL_YYYYMMDD_P5DOW, CAL_YYYYMMDD_P6DOW, CAL_YYYYMMDD_P7DOW, CAL_YYYYMMDD_P8DOW, CAL_YYYYMMDD_P9DOW, CAL_YYYYMMDD_P10DOW, CAL_YYYYMMDD_P1DOM, CAL_YYYYMMDD_P2DOM,
        CAL_YYYYMMDD_P1DOY, CAL_YYYYMMDD_P2DOY,  CAL_YYYYMMDD_P1DOWIM, CAL_YYYYMMDD_P2DOWIM, CAL_YYYYMM_P1DOWIM, CAL_YYYYMM_P2DOWIM, CAL_YYYY_P1DOWIM, CAL_YYYY_P2DOWIM,

        CAL_YYYYMM8_01,CAL_YYYYMM8_LD,
        CAL_YYYYMMDD8_YESTERDAY,CAL_YYYYMMDD8_TODAY,
        CAL_YYYYMMDD8,
        CAL_YYYYMMDD8_P1D, CAL_YYYYMMDD8_P2D,CAL_YYYYMMDD8_P3D, CAL_YYYYMMDD8_P4D,CAL_YYYYMMDD8_P5D,CAL_YYYYMMDD8_P6D, CAL_YYYYMMDD8_P7D,
        CAL_YYYYMMDD8_P8D, CAL_YYYYMMDD8_P9D,CAL_YYYYMMDD8_P10D, CAL_YYYYMMDD8_P11D,CAL_YYYYMMDD8_P12D,CAL_YYYYMMDD8_P13D, CAL_YYYYMMDD8_P14D,
        CAL_YYYYMMDD8_P15D, CAL_YYYYMMDD8_P16D,CAL_YYYYMMDD8_P17D, CAL_YYYYMMDD8_P18D,CAL_YYYYMMDD8_P19D,CAL_YYYYMMDD8_P20D, CAL_YYYYMMDD8_P21D,
        CAL_YYYYMMDD8_P22D, CAL_YYYYMMDD8_P23D,CAL_YYYYMMDD8_P24D, CAL_YYYYMMDD8_P25D,CAL_YYYYMMDD8_P26D,CAL_YYYYMMDD8_P27D, CAL_YYYYMMDD8_P28D,CAL_YYYYMMDD8_P29D,CAL_YYYYMMDD8_P30D,
        CAL_YYYYMMDD8_P1M, CAL_YYYYMMDD8_P2M, CAL_YYYYMMDD8_P3M, CAL_YYYYMMDD8_P4M,CAL_YYYYMMDD8_P5M, CAL_YYYYMMDD8_P6M, CAL_YYYYMMDD8_P7M, CAL_YYYYMMDD8_P8M, CAL_YYYYMMDD8_P9M, CAL_YYYYMMDD8_P10M, CAL_YYYYMMDD8_P11M, CAL_YYYYMMDD8_P12M,
        CAL_YYYYMMDD8_P1Y, CAL_YYYYMMDD8_P2Y, CAL_YYYYMMDD8_N1D, CAL_YYYYMMDD8_N2D, CAL_YYYYMMDD8_N1M, CAL_YYYYMMDD8_N2M, CAL_YYYYMMDD8_N1Y, CAL_YYYYMMDD8_N2Y, CAL_YYYYMM_N1D, CAL_YYYYMM_N2D, CAL_YYYYMM_N1M, CAL_YYYYMM_N2M, CAL_YYYYMM_N1Y, CAL_YYYYMM_N2Y, CAL_YYYY_N1D, CAL_YYYY_N2D, CAL_YYYY_N1M, CAL_YYYY_N2M, CAL_YYYY_N1Y, CAL_YYYY_N2Y, CAL_YYYYMMDD8_P1DOW, CAL_YYYYMMDD8_P2DOW, CAL_YYYYMMDD8_P3DOW, CAL_YYYYMMDD8_P4DOW, CAL_YYYYMMDD8_P5DOW, CAL_YYYYMMDD8_P6DOW, CAL_YYYYMMDD8_P7DOW, CAL_YYYYMMDD8_P8DOW, CAL_YYYYMMDD8_P9DOW, CAL_YYYYMMDD8_P10DOW, CAL_YYYYMM_P1DOW, CAL_YYYYMM_P2DOW, CAL_YYYY_P1DOW, CAL_YYYY_P2DOW, CAL_YYYYMMDD8_P1DOM, CAL_YYYYMMDD8_P2DOM, CAL_YYYYMM_P1DOM, CAL_YYYYMM_P2DOM, CAL_YYYY_P1DOM, CAL_YYYY_P2DOM, CAL_YYYYMMDD8_P1DOY, CAL_YYYYMMDD8_P2DOY, CAL_YYYYMM_P1DOY, CAL_YYYYMM_P2DOY, CAL_YYYY_P1DOY, CAL_YYYY_P2DOY, CAL_YYYYMMDD8_P1DOWIM, CAL_YYYYMMDD8_P2DOWIM,

        CAL_CUR_YYYYMM8_01,CAL_CUR_YYYYMM_01;

        public String toString() {
            return this.name().replace(DateConst.COMMON_VARS_CAL_PREFIX, "");
        }

        public String getVariableStr() {
            return "${".concat(this.name()).concat("}");
        }
    }
}